### ISSUE TITLE
日志获取异常，但是签到正常进行

### ISSUE THREAD

**Issue by RickHunterS** [MayoBlueSky/My-Actions#26]
百度签到日志异常报错：

**Comment by RickHunterS** [comment]
❗️百度签到, 错误!
Error: Cookie not in this host's domain. Cookie:baidu.com Request:null
    at CookieJar.setCookie (/home/runner/work/BlueSkyClouds-Actions/BlueSkyClouds-Actions/node_modules/tough-cookie/lib/cookie.js:1133:15)
    at CookieJar.setCookie (/home/runner/work/BlueSkyClouds-Actions/BlueSkyClouds-Actions/node_modules/tough-cookie/node_modules/universalify/index.js:5:67)
    at CookieJar.setCookieSync (/home/runner/work/BlueSkyClouds-Actions/BlueSkyClouds-Actions/node_modules/tough-cookie/lib/cookie.js:1642:21)
    at EventEmitter.isSurge.isLoon.isQuanX.isNode.got.on (/home/runner/work/BlueSkyClouds-Actions/BlueSkyClouds-Actions/function/tieba/tieba.js:[29](https://github.com/RickHunterS/BlueSkyClouds-Actions/runs/6366006248?check_suite_focus=true#step:5:29)3:4711)
    at EventEmitter.emit (events.js:198:13)
    at Request.fns.(anonymous function).args (/home/runner/work/BlueSkyClouds-Actions/BlueSkyClouds-Actions/node_modules/got/dist/source/core/utils/proxy-events.js:7:16)
    at Request.emit (events.js:198:13)
    at Request._onResponseBase (/home/runner/work/BlueSkyClouds-Actions/BlueSkyClouds-Actions/node_modules/got/dist/source/core/index.js:895:22)
    at Request._onResponse (/home/runner/work/BlueSkyClouds-Actions/BlueSkyClouds-Actions/node_modules/got/dist/source/core/index.js:940:24)
    at ClientRequest.request.once (/home/runner/work/BlueSkyClouds-Actions/BlueSkyClouds-Actions/node_modules/got/dist/source/core/index.js:954:23)

**Comment by RickHunterS** [comment]
方糖server酱能正常收到推送，但是签到天数等信息全部都是undefined。查看贴吧实际签到情况，签到可以正常进行，应该只是日志的问题。

**Comment by BlueSkyClouds** [comment]
拉取下最新的再试试

**Comment by BlueSkyClouds** [comment]
看样子解决了 close
